server {
    listen 80;
    listen [::]:80;
    server_name asyusha.space www.asyusha.space;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location / {
        return 301 https://asyusha.space$request_uri;
    }
}
